package primerproyectoanálisis;
import algoritmos.MaximoBeneficio;
import algoritmos.ejerC;
import algoritmos.cantMaxRest;
import algoritmos.greedy;
import grafo.Grafo;

public class PrimerProyectoAnálisis {

        public static Grafo grafo1 = new Grafo();
        public static Grafo grafo2 = new Grafo();
        public static Grafo grafo3 = new Grafo();
        public static Grafo grafo4 = new Grafo();
        public static Grafo grafo5 = new Grafo();
        public static Grafo grafo6 = new Grafo();

        public static greedy greedy = new greedy();
        public static MaximoBeneficio maximoBeneficio = new MaximoBeneficio();
        public static ejerC ejerC = new ejerC();
        public static cantMaxRest cantMaxRest = new cantMaxRest();
        
        static void crearGrafos(){
            grafo1.insercionVertices(13, "Santa Clara");
            grafo1.insercionVertices(4, "Florencia");
            grafo1.insercionVertices(9, "Muelle");
            grafo1.insercionVertices(6,"Cerro Cortez");
            grafo1.insercionVertices(8, "Arenal");
            grafo1.insercionVertices(7, "Cutris");

            grafo1.insertarArco("Florencia", "Muelle");
            grafo1.insertarArco("Santa Clara", "Muelle");
            grafo1.insertarArco("Muelle", "Cerro Cortez");
            grafo1.insertarArco("Muelle", "Florencia");
            grafo1.insertarArco("Muelle", "Santa Clara");
            grafo1.insertarArco("Cerro Cortez", "Muelle");
            grafo1.insertarArco("Cerro Cortez", "Cutris");
            grafo1.insertarArco("Cerro Cortez", "Arenal");
            grafo1.insertarArco("Arenal", "Cerro Cortez");
            grafo1.insertarArco("Cutris", "Cerro Cortez");

            grafo2.insercionVertices(9,"Aguaz Zarcas");
            grafo2.insercionVertices(10,"Pital");
            grafo2.insercionVertices(5, "Venecia");
            grafo2.insercionVertices(20,"Rio Cuarto");
            grafo2.insercionVertices(7,"La Tabla");
            grafo2.insercionVertices(3, "Santa Rita");
            grafo2.insercionVertices(12, "La Flor");
            grafo2.insercionVertices(11, "La Merced");
            grafo2.insercionVertices(4, "Santa Isabel");
            grafo2.insercionVertices(8, "San Miguel");
            
            grafo2.insertarArco("Aguaz Zarcas", "Pital");
            grafo2.insertarArco("Pital", "Aguaz Zarcas");
            grafo2.insertarArco("Pital", "Venecia");
            grafo2.insertarArco("Venecia", "Pital");
            grafo2.insertarArco("Venecia", "Rio Cuarto");
            grafo2.insertarArco("Venecia", "La Tabla");
            grafo2.insertarArco("La Tabla", "Venecia");
            grafo2.insertarArco("La Tabla", "Santa Rita");
            grafo2.insertarArco("La Tabla", "La Merced");
            grafo2.insertarArco("La Tabla", "La Flor");
            grafo2.insertarArco("Santa Rita", "La Tabla");
            grafo2.insertarArco("La Merced", "La Tabla");
            grafo2.insertarArco("La Merced", "Santa Isabel");
            grafo2.insertarArco("La Merced", "San Miguel");
            grafo2.insertarArco("Santa Isabel", "La Merced");
            grafo2.insertarArco("San Miguel", "La Merced");
            grafo2.insertarArco("La Flor", "La Tabla");
            grafo2.insertarArco("Rio Cuarto", "Venecia");
            
            grafo3.insercionVertices(12,"San Ramon");
            grafo3.insercionVertices(7,"Zarcero");
            grafo3.insercionVertices(6,"Naranjo");
            grafo3.insercionVertices(10,"Ciudad Quesada");
            grafo3.insercionVertices(15,"Aguaz Zarcas");
            grafo3.insercionVertices(11,"Muelle");
            grafo3.insercionVertices(5,"Fortuna");
            grafo3.insercionVertices(14,"Santa Clara");
            grafo3.insercionVertices(4,"Florencia");
            grafo3.insercionVertices(2,"Rio Cuarto");
            grafo3.insercionVertices(8,"Santa Rita");
            grafo3.insercionVertices(1,"Santa Isabel");
            grafo3.insercionVertices(13,"Pital");
            grafo3.insercionVertices(3,"Puerto Escondido");
            grafo3.insercionVertices(9,"Veracruz");
            
            grafo3.insertarArco("San Ramon", "Zarcero");
            grafo3.insertarArco("Zarcero", "San Ramon");
            grafo3.insertarArco("Zarcero", "Naranjo");
            grafo3.insertarArco("Zarcero", "Ciudad Quesada");
            grafo3.insertarArco("Naranjo", "Zarcero");
            grafo3.insertarArco("Ciudad Quesada", "Zarcero");
            grafo3.insertarArco("Ciudad Quesada", "Aguaz Zarcas");
            grafo3.insertarArco("Aguaz Zarcas", "Ciudad Quesada");
            grafo3.insertarArco("Aguaz Zarcas", "Pital");
            grafo3.insertarArco("Aguaz Zarcas", "Muelle");
            grafo3.insertarArco("Aguaz Zarcas", "Rio Cuarto");
            grafo3.insertarArco("Rio Cuarto", "Santa Rita");
            grafo3.insertarArco("Rio Cuarto", "Aguaz Zarcas");
            grafo3.insertarArco("Santa Rita", "Rio Cuarto");
            grafo3.insertarArco("Santa Rita", "Santa Isabel");
            grafo3.insertarArco("Santa Isabel", "Santa Rita");
            grafo3.insertarArco("Pital", "Aguaz Zarcas");
            grafo3.insertarArco("Pital", "Veracruz");
            grafo3.insertarArco("Pital", "Puerto Escondido");
            grafo3.insertarArco("Veracruz", "Pital");
            grafo3.insertarArco("Puerto Escondido", "Pital");
            grafo3.insertarArco("Muelle", "Aguaz Zarcas");
            grafo3.insertarArco("Muelle", "Fortuna");
            grafo3.insertarArco("Muelle", "Santa Clara");
            grafo3.insertarArco("Fortuna", "Muelle");
            grafo3.insertarArco("Florencia", "Santa Clara");
            grafo3.insertarArco("Santa Clara", "Muelle");
            grafo3.insertarArco("Santa Clara", "Florencia");
            
            grafo4.insercionVertices(1,"Rio Cuarto");
            grafo4.insercionVertices(2,"Santa Rosa");
            grafo4.insercionVertices(3,"Veracruz");
            grafo4.insercionVertices(4,"Cutris");
            grafo4.insercionVertices(5,"San Gerardo");
            grafo4.insercionVertices(6,"Sucre");
            grafo4.insercionVertices(7,"La Virgen");
            grafo4.insercionVertices(8,"Desamparados");
            grafo4.insercionVertices(9,"Barrio Mexico");
            grafo4.insercionVertices(10,"Pocosol");
            grafo4.insercionVertices(11,"La Palmera");
            grafo4.insercionVertices(12,"Pital");
            grafo4.insercionVertices(13,"Golfito");
            grafo4.insercionVertices(14,"Venado");
            grafo4.insercionVertices(15,"Puerto V");
            grafo4.insercionVertices(16,"Venecia");
            grafo4.insercionVertices(17,"Roomoser");
            grafo4.insercionVertices(18,"Alajuela");
            grafo4.insercionVertices(19,"Moravia");
            grafo4.insercionVertices(20,"Perez Z");
            /*
            grafo4.insertarArco(1,12);
            grafo4.insertarArco(12,1);
            grafo4.insertarArco(12,19);
            grafo4.insertarArco(19,12);
            grafo4.insertarArco(12,16);
            grafo4.insertarArco(16,12);
            grafo4.insertarArco(16,4);
            grafo4.insertarArco(4,16);
            grafo4.insertarArco(4,17);
            grafo4.insertarArco(17,4);
            grafo4.insertarArco(4,18);
            grafo4.insertarArco(18,4);
            grafo4.insertarArco(18,14);
            grafo4.insertarArco(14,18);
            grafo4.insertarArco(18,2);
            grafo4.insertarArco(2,18);
            grafo4.insertarArco(17,11);
            grafo4.insertarArco(11,17);
            grafo4.insertarArco(11,13);
            grafo4.insertarArco(13,11);
            grafo4.insertarArco(13,3);
            grafo4.insertarArco(3,11);
            grafo4.insertarArco(13,9);
            grafo4.insertarArco(9,13);
            grafo4.insertarArco(9,20);
            grafo4.insertarArco(20,9);
            grafo4.insertarArco(20,15);
            grafo4.insertarArco(15,20);
            grafo4.insertarArco(20,7);
            grafo4.insertarArco(7,20);
            grafo4.insertarArco(7,6);
            grafo4.insertarArco(6,7);
            grafo4.insertarArco(6,5);
            grafo4.insertarArco(5,6);
            */
            grafo5.insercionVertices(1,"Estados Unidos");
            grafo5.insercionVertices(2,"Venezuela");
            grafo5.insercionVertices(3,"Nicaragua");
            grafo5.insercionVertices(4,"El Salvador");
            grafo5.insercionVertices(5,"Argentina");
            grafo5.insercionVertices(6,"Paraguay");
            grafo5.insercionVertices(7,"Mexico");
            grafo5.insercionVertices(8,"Colombia");
            grafo5.insercionVertices(9,"Ecuador");
            grafo5.insercionVertices(10,"Chile");
            grafo5.insercionVertices(11,"Guatemala");
            grafo5.insercionVertices(12,"Surinam");
            grafo5.insercionVertices(13,"Haiti");
            grafo5.insercionVertices(14,"Canda");
            grafo5.insercionVertices(15,"Belice");
            grafo5.insercionVertices(16,"Brasil");
            grafo5.insercionVertices(17,"Panama");
            grafo5.insercionVertices(18,"Guyana Francesa");
            grafo5.insercionVertices(19,"Uruguay");
            grafo5.insercionVertices(20,"Costa Rica");
            grafo5.insercionVertices(21,"Rep. Dominicana <3");
            grafo5.insercionVertices(22,"Honduras");
            grafo5.insercionVertices(23,"Cuba");
            grafo5.insercionVertices(24,"Peru");
            grafo5.insercionVertices(25,"Bolivia");
            /*
            grafo5.insertarArco(1,20);
            grafo5.insertarArco(20, 1);
            grafo5.insertarArco(20,7);
            grafo5.insertarArco(7, 20);
            grafo5.insertarArco(20,15);
            grafo5.insertarArco(15, 20);
            grafo5.insertarArco(20,14);
            grafo5.insertarArco(14, 20);
            grafo5.insertarArco(14,4);
            grafo5.insertarArco(4, 14);
            grafo5.insertarArco(4,11);
            grafo5.insertarArco(11, 4);
            grafo5.insertarArco(15,22);
            grafo5.insertarArco(22, 15);
            grafo5.insertarArco(22,25);
            grafo5.insertarArco(25, 22);
            grafo5.insertarArco(25,5);
            grafo5.insertarArco(5, 25);
            grafo5.insertarArco(5,24);
            grafo5.insertarArco(24, 5);
            grafo5.insertarArco(24,10);
            grafo5.insertarArco(10, 24);
            grafo5.insertarArco(24,16);
            grafo5.insertarArco(16, 24);
            grafo5.insertarArco(10, 24);
            grafo5.insertarArco(16,8);
            grafo5.insertarArco(8, 16);
            grafo5.insertarArco(8,2);
            grafo5.insertarArco(2, 8);
            grafo5.insertarArco(24,23);
            grafo5.insertarArco(23, 24);
            grafo5.insertarArco(23,12);
            grafo5.insertarArco(12, 23);
            grafo5.insertarArco(23,21);
            grafo5.insertarArco(21, 23);
            grafo5.insertarArco(23,3);
            grafo5.insertarArco(3, 23);
            grafo5.insertarArco(21,13);
            grafo5.insertarArco(13, 21);
            grafo5.insertarArco(3,9);
            grafo5.insertarArco(9, 3);
            grafo5.insertarArco(12,18);
            grafo5.insertarArco(18, 12);
            grafo5.insertarArco(18,6);
            grafo5.insertarArco(6, 18);
            grafo5.insertarArco(6,19);
            grafo5.insertarArco(19, 6);
            grafo5.insertarArco(6,17);
            grafo5.insertarArco(17, 6);*/
            
            grafo6.insercionVertices(1,"Estados Unidos");
            grafo6.insercionVertices(2,"Venezuela");
            grafo6.insercionVertices(3,"Nicaragua");
            grafo6.insercionVertices(4,"El Salvador");
            grafo6.insercionVertices(5,"Argentina");
            grafo6.insercionVertices(6,"Paraguay");
            grafo6.insercionVertices(7,"Mexico");
            grafo6.insercionVertices(8,"Colombia");
            grafo6.insercionVertices(9,"Ecuador");
            grafo6.insercionVertices(10,"Chile");
            grafo6.insercionVertices(11,"Guatemala");
            grafo6.insercionVertices(12,"Surinam");
            grafo6.insercionVertices(13,"Haiti");
            grafo6.insercionVertices(14,"Canda");
            grafo6.insercionVertices(15,"Belice");
            grafo6.insercionVertices(16,"Brasil");
            grafo6.insercionVertices(17,"Panama");
            grafo6.insercionVertices(18,"Guyana Francesa");
            grafo6.insercionVertices(19,"Uruguay");
            grafo6.insercionVertices(20,"Costa Rica");
            grafo6.insercionVertices(21,"Rep. Dominicana <3");
            grafo6.insercionVertices(22,"Honduras");
            grafo6.insercionVertices(23,"Cuba");
            grafo6.insercionVertices(24,"Peru");
            grafo6.insercionVertices(25,"Bolivia");        
        }
        
        static void desmarcar(){
            grafo1.desmarcar();
            grafo2.desmarcar();
            grafo3.desmarcar();
            grafo4.desmarcar();
            grafo5.desmarcar();
            grafo6.desmarcar();    
        }
        
        public static void main(String[] args) {
                crearGrafos();               
                System.out.println("-Max Beneficio");
                maximoBeneficio.maximoBeneficio(grafo2);
       
        }
        
}
